import { Component } from '@angular/core';
import { SharedModule } from '../../../shared/shared.module';
import { SpkReusableTablesComponent } from "../../../@spk/reusable-tables/spk-reusable-tables/spk-reusable-tables.component";

@Component({
  selector: 'app-transactions',
  standalone: true,
  imports: [SharedModule, SpkReusableTablesComponent],
  templateUrl: './transactions.component.html',
  styleUrl: './transactions.component.scss'
})
export class TransactionsComponent {
  transactionColumns=[
    {header:'S.NO',field:'S.NO'},
    {header:'TRANSACTION HASH',field:'TRANSACTION HASH'},
    {header:'Date',field:'Date'},
    {header:'From',field:'From'},
    {header:'To',field:'To'},
    {header:'Coin',field:'Coin'},
    {header:'Amount',field:'Amount'},
    {header:'Status',field:'Status'},

  ]
  transactions = [
    {
      id: '#1242232401',
      date: '03/12/2020',
      customer: 'Olive Yew',
      avatar: './assets/images/faces/2.jpg',
      partner: 'Peg Legge',
      currencyIcon: './assets/images/svgs/crypto-currencies/btc.svg',
      currency: 'Bitcoin',
      amount: '+0.041',
      amountClass: 'text-success',
      status: 'COMPLETED',
      statusClass: 'text-success',
      arrowClass: 'fe-arrow-up-right',
    },
    {
      id: '#1242232402',
      date: '05/12/2020',
      customer: 'Addie Minstra',
      avatar: './assets/images/faces/3.jpg',
      partner: 'Art Decco',
      currencyIcon: './assets/images/svgs/crypto-currencies/eth.svg',
      currency: 'Ethereum',
      amount: '-0.344',
      amountClass: 'text-danger',
      status: 'CANCELED',
      statusClass: 'text-danger',
      arrowClass: 'fe-arrow-down-left',
    },
    {
      id: '#1242232403',
      date: '14/12/2020',
      customer: 'Stan Dupp',
      avatar: './assets/images/faces/4.jpg',
      partner: 'Neil Down',
      currencyIcon: './assets/images/svgs/crypto-currencies/xrp.svg',
      currency: 'Ripple',
      amount: '-0.345',
      amountClass: 'text-muted',
      status: 'PENDING',
      statusClass: 'text-muted',
      arrowClass: 'fe-arrow-down-left',
    },
    {
      id: '#1242232404',
      date: '16/12/2020',
      customer: 'Penny Black',
      avatar: './assets/images/faces/5.jpg',
      partner: 'Anna Domino',
      currencyIcon: './assets/images/svgs/crypto-currencies/dash.svg',
      currency: 'Dash',
      amount: '+0.132',
      amountClass: 'text-success',
      status: 'COMPLETED',
      statusClass: 'text-success',
      arrowClass: 'fe-arrow-up-right',
    },
    {
      id: '#1242232405',
      date: '18/12/2020',
      customer: 'Phil Harmonic',
      avatar: './assets/images/faces/6.jpg',
      partner: 'Paul Misunday',
      currencyIcon: './assets/images/svgs/crypto-currencies/ltc.svg',
      currency: 'Litecoin',
      amount: '-0.523',
      amountClass: 'text-danger',
      status: 'CANCELED',
      statusClass: 'text-danger',
      arrowClass: 'fe-arrow-down-left',
    },
    {
      id: '#1242232406',
      date: '20/12/2020',
      customer: 'Arty Ficial',
      avatar: './assets/images/faces/7.jpg',
      partner: 'Marsha Mello',
      currencyIcon: './assets/images/svgs/crypto-currencies/xmr.svg',
      currency: 'Monero',
      amount: '-0.232',
      amountClass: 'text-muted',
      status: 'PENDING',
      statusClass: 'text-muted',
      arrowClass: 'fe-arrow-down-left',
    },
    {
      id: '#1242232407',
      date: '22/12/2020',
      customer: 'Donatella Nobatti',
      avatar: './assets/images/faces/8.jpg',
      partner: 'Peg Legge',
      currencyIcon: './assets/images/svgs/crypto-currencies/steem.svg',
      currency: 'Steem',
      amount: '+0.456',
      amountClass: 'text-success',
      status: 'COMPLETED',
      statusClass: 'text-success',
      arrowClass: 'fe-arrow-up-right',
    },
    {
      id: '#1242232408',
      date: '25/12/2020',
      customer: 'Juan Annatoo',
      avatar: './assets/images/faces/9.jpg',
      partner: 'Jack Dup',
      currencyIcon: './assets/images/svgs/crypto-currencies/miota.svg',
      currency: 'Iota',
      amount: '+0.232',
      amountClass: 'text-success',
      status: 'COMPLETED',
      statusClass: 'text-success',
      arrowClass: 'fe-arrow-up-right',
    },
    {
      id: '#1242232409',
      date: '25/12/2020',
      customer: 'Stew Gots',
      avatar: './assets/images/faces/10.jpg',
      partner: 'Sara Bellum',
      currencyIcon: './assets/images/svgs/crypto-currencies/waves.svg',
      currency: 'Waves',
      amount: '-0.232',
      amountClass: 'text-muted',
      status: 'PENDING',
      statusClass: 'text-muted',
      arrowClass: 'fe-arrow-down-left',
    },
    {
      id: '#1242232410',
      date: '28/12/2020',
      customer: 'Anna Rexia',
      avatar: './assets/images/faces/11.jpg',
      partner: 'Marge Arita',
      currencyIcon: './assets/images/svgs/crypto-currencies/neo.svg',
      currency: 'Neo',
      amount: '-0.344',
      amountClass: 'text-danger',
      status: 'CANCELED',
      statusClass: 'text-danger',
      arrowClass: 'fe-arrow-down-left',
    },
    {
      id: '#1242232411',
      date: '29/12/2020',
      customer: 'Matt Innae',
      avatar: './assets/images/faces/12.jpg',
      partner: 'Barry Cuda',
      currencyIcon: './assets/images/svgs/crypto-currencies/eos.svg',
      currency: 'Eos',
      amount: '-0.231',
      amountClass: 'text-danger',
      status: 'CANCELED',
      statusClass: 'text-danger',
      arrowClass: 'fe-arrow-down-left',
    },
    {
      id: '#1242232412',
      date: '30/12/2020',
      customer: 'Gabe Lackmen',
      avatar: './assets/images/faces/1.jpg',
      partner: 'Marion Gaze',
      currencyIcon: './assets/images/svgs/crypto-currencies/eur.svg',
      currency: 'Euros',
      amount: '+0.124',
      amountClass: 'text-success',
      status: 'COMPLETED',
      statusClass: 'text-success',
      arrowClass: 'fe-arrow-up-right',
    },
    {
      id: '#1242232413',
      date: '31/12/2020',
      customer: 'Jim Nasium',
      avatar: './assets/images/faces/2.jpg',
      partner: 'Marcus Down',
      currencyIcon: './assets/images/svgs/crypto-currencies/btc.svg',
      currency: 'Bitcoin',
      amount: '-0.241',
      amountClass: 'text-muted',
      status: 'PENDING',
      statusClass: 'text-muted',
      arrowClass: 'fe-arrow-down-left',
    },
    {
      id: '#1242232414',
      date: '02/01/2021',
      customer: 'Ella Vator',
      avatar: './assets/images/faces/3.jpg',
      partner: 'Gene Jacket',
      currencyIcon: './assets/images/svgs/crypto-currencies/eth.svg',
      currency: 'Ethereum',
      amount: '+0.134',
      amountClass: 'text-success',
      status: 'COMPLETED',
      statusClass: 'text-success',
      arrowClass: 'fe-arrow-up-right',
    },
    {
      id: '#1242232415',
      date: '04/01/2021',
      customer: 'Bart Ender',
      avatar: './assets/images/faces/4.jpg',
      partner: 'Marty Graw',
      currencyIcon: './assets/images/svgs/crypto-currencies/xrp.svg',
      currency: 'Ripple',
      amount: '-0.244',
      amountClass: 'text-muted',
      status: 'PENDING',
      statusClass: 'text-muted',
      arrowClass: 'fe-arrow-down-left',
    },
    // Add more transactions as required
  ];
}
